"""empty message

Revision ID: 5030a5d18a6d
Revises: 89aea6655b75
Create Date: 2018-07-08 10:48:02.588979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5030a5d18a6d'
down_revision = '89aea6655b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('private_post', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'private_post')
    # ### end Alembic commands ###
