"""empty message

Revision ID: a2be6e1adca8
Revises: 5030a5d18a6d
Create Date: 2018-07-08 11:03:22.994636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2be6e1adca8'
down_revision = '5030a5d18a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'author_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('comments', 'author_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'header',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('posts', 'header',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'author_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('comments', 'author_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
